export const USER_ROLES = {
  MANAGER: "MANAGER",
  EXECUTIVE: "EXECUTIVE",
  CUSTOMER: "CUSTOMER",
  GENERAL: "GENERAL",
  ORDER_MANAGER: "ORDER_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  MARCKETING_MANAGER: "MARCKETING_MANAGER",
  TRANSPORT_MANAGER: "TRANSPORT_MANAGER",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  SALES_MANAGER: "SALES_MANAGER",
  SUPPLIER_MANAGER: "SUPPLIER_MANAGER"
  
};